name: TpsSpoofer
version: ${project.version}
main: lol.maltest.tpsspoofer.TpsSpoofer
authors: [maltest]
description: tps spoofer cause im bored and need stuff for my github ok thanks lol
website: maltest.lol
commands:
  tps:
    description: Shows the server tps!